apiVersion: v1
kind: Service
metadata:
  name: is-service
  namespace: default
spec:
  selector:
    app: istrav-subvind
  ports:
  - protocol: TCP
    port: 1337
    targetPort: 1337
  type: NodePort